---
- name: Install Docker and run demo container
  hosts: all
  become: yes
  vars:
    default_container_image: 10.66.41.133:5000/vision-sensus-emul:5.2.2.5-3.9.6.9

    
  tasks:
    - set_fact:
        ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Run apt upgrade
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 432000
    
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
  

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes
      ignore_errors: yes

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    #- name: Pull default Docker image
    #  community.docker.docker_image:
    #    name: "{{ default_container_image }}"
    #    source: pull

    - name: Create default containers
      community.docker.docker_container:
        name: demo_emulator
        image: "{{ default_container_image }}"
        ports:
          - "8400:8400"
        state: started
